apps/dasa/forms.py
# encoding=utf-8
#
# copyright Gerbrandy SRL
# www.gerbrandy.com
# 2013
#


import random
import re

try:
    from hashlib import sha1 as sha_constructor
except ImportError:
    from django.utils.hashcompat import sha_constructor

from django.db import models as django_models
from django import forms
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth import authenticate

from haystack.forms import model_choices, SearchQuerySet, EmptySearchQuerySet
from haystack.inputs import BaseInput, Clean, Exact, Not
from haystack.query import SQ

from userena.forms import SignupFormOnlyEmail
from userena.utils import get_profile_model, get_user_model
from userena import settings as userena_settings
from userena.models import UserenaSignup
from userena import forms as userena_forms

from django_countries import countries

from dasa import lookups
from dasa import models

import selectable

INPUT_FORMATS = [
    '%d-%m-%y',
    '%d/%m/%y',
    '%d-%m-%Y',
    '%d/%m/%Y',
    '%d %b %Y',
    '%d %B %Y',
    '%Y-%m-%d',
    '%Y-%m-%d',
    '%m/%d/%Y',
    '%m/%d/%y',
]

JQUERY_UI_ATTRS = {'class': 'ui-widget ui-widget-content ui-corner-all'}


class DasaQuery(BaseInput):
    """
    A convenience class that handles common user queries.

    In addition to cleaning all tokens, it handles double quote bits as
    exact matches & terms with '-' in front as NOT queries.
    """
    input_type_name = 'auto_query'
    post_process = False
    exact_match_re = re.compile(r'"(?P<phrase>.*?)"')
    boolean_operators = ['AND', 'OR', 'NOT']

    def prepare(self, query_obj):
        query_string = super(DasaQuery, self).prepare(query_obj)
        exacts = self.exact_match_re.findall(query_string)
        tokens = []
        query_bits = []

        for rough_token in self.exact_match_re.split(query_string):
            if not rough_token:
                continue
            elif rough_token not in exacts:
                # We have something that's not an exact match but may have more
                # than on word in it.
                tokens.extend(rough_token.split(' '))
            else:
                tokens.append(rough_token)

        for token in tokens:
            if not token:
                continue
            elif token in self.boolean_operators:
                query_bits.append(token)
            elif token in exacts:
                query_bits.append(Exact(token, clean=True).prepare(query_obj))
            elif token.startswith('-') and len(token) > 1:
                # This might break Xapian. Check on this.
                query_bits.append(Not(token[1:]).prepare(query_obj))
            else:
                query_bits.append(Clean(token).prepare(query_obj))

        return u' '.join(query_bits)


class SearchForm(forms.Form):
    """adapted from haystack.forms.SearchForm"""

    searchqueryset = None

    def __init__(self, *args, **kwargs):

        if not self.searchqueryset:
            self.searchqueryset = kwargs.pop('searchqueryset', None)
        self.load_all = kwargs.pop('load_all', False)

        if self.searchqueryset is None:
            self.searchqueryset = SearchQuerySet()

        super(SearchForm, self).__init__(*args, **kwargs)

    def no_query_found(self):
        """
        Determines the behavior when no query was found.

        By default, no results are returned (``EmptySearchQuerySet``).

        Should you want to show all results, override this method in your
        own ``SearchForm`` subclass and do ``return self.searchqueryset.all()``.
        """
        return EmptySearchQuerySet()

    def search(self):
        if not self.is_valid():
            return self.no_query_found()

        if not self.cleaned_data.get('q'):
            return self.no_query_found()

        if self.cleaned_data['q']:
            sqs = self.searchqueryset.filter(content=DasaQuery(self.cleaned_data['q']))

        if self.load_all:
            sqs = sqs.load_all()

        return sqs

    def get_suggestion(self):
        if not self.is_valid():
            return None

        return self.searchqueryset.spelling_suggestion(self.cleaned_data['q'])


class SiteSearchForm(SearchForm):
    """Form for site-wide search"""

    attrs = {'type': 'search'}
    attrs.update(JQUERY_UI_ATTRS)
    q = forms.CharField(required=False, label=_('Search'), widget=forms.TextInput(attrs=attrs))

    mapchoice2models = {
        'all': [x[0] for x in model_choices() if x[0] not in ['dasa.journalentryclass', 'dasa.resolutionclass']],
        'hartakarun': ['dasa.hartakaruncategory', 'dasa.hartakarunmaincategory', 'dasa.hartakarunitem'],
        'journalentries': ['dasa.journalentry', ],
        'resolutions': ['dasa.resolution'],
        'diplomaticletters': ['dasa.diplomaticletter', 'dasa.diplomaticletterlocation', 'dasa.diplomaticletterruler'],
        'retrobooks': ['dasa.retrobookscan', 'dasa.retrobook'],
        'hartakarun_items': ['dasa.hartakarunitem'],
        'placards': ['dasa.placard'],
        'appendices': ['dasa.appendix'],
        'corpusdiplomaticumcontracts': ['dasa.corpusdiplomaticumcontract'],
        'maps': ['dasa.dehaan'],
    }

    def __init__(self, *args, **kwargs):

        super(SiteSearchForm, self).__init__(*args, label_suffix='', **kwargs)
        self.choices = [
            ('all', _('Entire site')),
            ('hartakarun', _('Harta Karun Categories')),
            ('hartakarun_items', _('Harta Karun Articles')),
            ('journalentries', _('Marginalia to the Daily Journals')),
            ('resolutions', _('Realia to the Resolutions and Besognes')),
            ('diplomaticletters', _('Diplomatic Letters')),
            ('placards', _('Placards')),
            ('appendices', _('Appendices Resolutions')),
            ('corpusdiplomaticumcontracts', _('Corpus Diplomaticum Contracts')),
            ('maps', _('Maps')),
            ]
        choices = self.choices
        self.fields['models'] = forms.MultipleChoiceField(
            choices=choices, required=False, label=_('Search In'),
            widget=forms.CheckboxSelectMultiple(),
            )

    def get_models(self):
        """Return an alphabetical list of model classes in the index."""
        search_models = []
        if self.is_valid():
            choices = self.cleaned_data['models']
            if not choices:
                choices = ['all']
            if not isinstance(choices, type([])):
                choices = [choices]
            for choice in choices:
                for model in self.mapchoice2models[choice]:
                    search_models.append(django_models.get_model(*model.split('.')))

        return list(set(search_models))

    def search(self):
        sqs = super(SiteSearchForm, self).search()
        sqs = sqs.models(*self.get_models())
        return sqs


class MarginaliaSearchForm(SearchForm):
    searchqueryset = SearchQuerySet().models(models.JournalEntry)

    def __init__(self, *args, **kwargs):
        super(MarginaliaSearchForm, self).__init__(*args, label_suffix='', **kwargs)

    description = forms.CharField(
        label=_('Description'),
        widget=forms.TextInput(attrs=JQUERY_UI_ATTRS),
        required=False,
    )

    date_from = forms.DateField(
        required=False,
        label=_('Date from'),
        widget=forms.widgets.DateInput(attrs=JQUERY_UI_ATTRS),
        )

    date_to = forms.DateField(
        label=_('Date to'),
        required=False,
        widget=forms.widgets.DateInput(attrs=JQUERY_UI_ATTRS),
        )

    vessel_name = forms.CharField(
        label=_('Ship name'),
        widget=selectable.forms.AutoCompleteWidget(lookups.VesselNameLookup, allow_new=True),
        required=False,
    )

    european_name = forms.CharField(
        label=_('European name'),
        widget=selectable.forms.AutoCompleteWidget(lookups.MarginaliaEuropeanNameLookup, allow_new=True),
        required=False,
    )

    asian_name = forms.CharField(
        label=_('Asian name'),
        widget=selectable.forms.AutoCompleteWidget(lookups.MarginaliaAsianNameLookup, allow_new=True),
        required=False,
    )

    place_name = forms.CharField(
        label=_('Place name'),
        widget=selectable.forms.AutoCompleteWidget(lookups.MarginaliaPlaceNameLookup, allow_new=True),
        required=False,
    )

    archiveFile = forms.CharField(
        label=_('Archive file'),
        widget=forms.widgets.TextInput(attrs=JQUERY_UI_ATTRS),
        required=False,
    )

    order_by = forms.CharField(required=False, widget=forms.HiddenInput())

    def search(self):
        # First, store the SearchQuerySet received from other processing.
        sqs = super(MarginaliaSearchForm, self).search()
        if self.is_valid():
            if self.cleaned_data.get('description'):
                sqs = sqs.filter(description=DasaQuery(self.cleaned_data['description']))
            if self.cleaned_data.get('date_from'):
                sqs = sqs.filter(date__gte=self.cleaned_data['date_from'])
            if self.cleaned_data.get('date_to'):
                sqs = sqs.filter(date__lte=self.cleaned_data['date_to'])
            if self.cleaned_data.get('vessel_name'):
                sqs = sqs.filter(vessel_names_list__exact=DasaQuery(self.cleaned_data['vessel_name']))
            if self.cleaned_data.get('asian_name'):
                sqs = sqs.filter(person_names_asian_list__exact=DasaQuery(self.cleaned_data['asian_name']))
            if self.cleaned_data.get('european_name'):
                sqs = sqs.filter(person_names_european_list__exact=DasaQuery(self.cleaned_data['european_name']))
            if self.cleaned_data.get('place_name'):
                sqs = sqs.filter(place_names_list__exact=DasaQuery(self.cleaned_data['place_name']))
            if self.cleaned_data.get('archiveFile'):
                sqs = sqs.filter(archiveFile=self.cleaned_data['archiveFile'])
            if self.cleaned_data.get('order_by'):

apps/dasa/templates/pages/appendix-asian-names.html
{% extends "basicpage.html" %}
{% load url from future %}
{% load thumbnail i18n %}

{% comment %}
XXX: body_id should be changed, but CSS depends on this id
{% endcomment %}
{% block body_id %}resolution_subjects{% endblock %}

{% block content %}
{{ block.super }}
<div class="alphabet">
    {% for letter, count in letters %}
    <a href="{% url SLUG_APPENDIX_ASIANNAMES %}?first_letter={{ letter }}">
        <span class="letter">{{letter}}</span>
        <br>
        <span class="count">
        {{ count }}
        </span>
    </a>
    {% endfor %}
</div>
<br class="clear" />
{% for col in names %}
	<div class="column">
	<ul>
	{% for name, nr in col %}
	<li>
	<a href="{% url SLUG_APPENDIX_SEARCH %}?asian_name={{ name }}&q=">
    {{ name }} ({{ nr }})
	</a>
	</li>
	{% endfor %}
	</ul>
</div>
{% endfor %}
{% endblock %}

apps/dasa/templates/pages/appendix-browse.html
{% extends "browse-and-search-template.html" %}
{% load thumbnail i18n highlight snippet %}

{% block js %}
{{ block.super }}
<script>
    $(document).ready(function() {
        $(document).tooltip();
 	});
</script>
{% endblock %}


{% block headers %}
    <tr class="headers">
        <th style="width:145px">
            <a href=".?{{ qs.order_by_archive_reference }}">
            {% trans "Archive Reference" %}
            </a>
        </th>
        <th style="width:90px">
            <a href=".?{{ qs.order_by_date }}">
            {% trans "Document Date" %}
            </a>
        </th>
        <th style="width: 300px">
            {% trans "Description" %}
        </th>
        {% comment %}
        <th>
            <a href=".?{{ qs.order_by_vessel_names }}">
            {% trans "Ship Names" %}
            </a>
        </th>
        {% endcomment %}
    </tr>
{% endblock headers %}

{% block result_row %}
    <tr {% ifequal selected_order result.order %}class="selected"{% endifequal %}>
        <td>
        {% if result.object.archiveFile in published_archivefiles %}
            <a href="#" onClick="return openPageBrowser('{{result.object.link_to_pagebrowser}}');">
                {{ result.object.archive_reference }}
                <img src="{{STATIC_URL}}images/book.png" style="float:right">
            </a>
        {% else %}
            {{ result.object.archive_reference }}
        {% endif %}
        </td>
        <td>
            {% if result.object.doc_date %}
            {{ result.object.doc_date }}
            {% endif %}
        </td>
        <td class="marginalia_description">
            {% if result.object.res_date %}
                {% trans "Resolution Date" %}: {{ result.object.res_date }}
                <br>
            {% endif %}
            {% if result.resolution_reference %}
                {{ result.resolution_reference }}
                <br>
            {% endif %}
            {% trans "Title" %}: {{ result.object.title_nl }}
            <br>
            {% trans "Document type" %}:
            <a href="{% url SLUG_APPENDIX_SEARCH %}?document_type={{ result.object.document_type_nl }}">{{ result.object.document_type_nl }}</a>

            {% if result.object.vessel_names %}
                <br>
                {% trans "Ship names" %}:
                {% for name in result.object.vessel_names_as_list %}
                    <a href="{% url SLUG_APPENDIX_SEARCH %}?vessel_name={{ name }}">{{ name }}</a>{% if forloop.last %}{%else%};{%endif%}
                {% endfor %}
            {% endif %}
            {% if result.object.person_names_european %}
                <br>
                {% trans "European names" %}:
                {% for name in result.object.person_names_european_list %}
                    <a href="{% url SLUG_APPENDIX_SEARCH %}?european_name={{ name }}">{{ name }}</a>{% if forloop.last %}{%else%};{%endif%}
                {% endfor %}
            {% endif %}

            {% if result.object.person_names_asian %}
                <br>
                {% trans "Asian names" %}:
                {% for name in result.object.person_names_asian_list %}
                    <a href="{% url SLUG_APPENDIX_SEARCH %}?asian_name={{ name }}">{{ name }}</a>{% if forloop.last %}{%else%};{%endif%}
                {% endfor %}
            {% endif %}
            {% if result.object.place_names %}
                <br>
                {% trans "Place names" %}:
                {% for name in result.object.place_names_list %}
                    <a href="{% url SLUG_APPENDIX_SEARCH %}?place_name={{ name }}">{{ name }}</a>{% if forloop.last %}{%else%};{%endif%}
                {% endfor %}
            {% endif %}
            {% if result.object.notes %}
            <br>
            {% trans "Notes" %}:
            {{ result.object.notes|default:"" }}
            {% endif %}

        </td>
        {% comment %}
        <td>
          {% if result.object.vessel_names %}
                {% for vessel_name in result.object.vessel_names_as_list %}
                    <a href="{% url SLUG_APPENDIX_SEARCH %}?vessel_name={{ vessel_name }}">{{ vessel_name }}</a>
                {% endfor %}
            {% endif %}
         </td>
        {% endcomment %}


    </tr>
{% endblock %}

apps/dasa/templates/pages/appendix-place-names.html
{% extends "basicpage.html" %}
{% load url from future %}
{% load thumbnail i18n %}

{% comment %}
XXX: body_id should be changed, but CSS depends on this id
{% endcomment %}
{% block body_id %}resolution_subjects{% endblock %}

{% block content %}
{{ block.super }}
<div class="alphabet">
    {% for letter, count in letters %}
    <a href="{% url SLUG_APPENDIX_PLACENAMES %}?first_letter={{ letter }}">
        <span class="letter">{{letter}}</span>
        <br>
        <span class="count">
        {{ count }}
        </span>
    </a>
    {% endfor %}
</div>
<br class="clear" />
{% for col in names %}
	<div class="column">
	<ul>
	{% for name, nr in col %}
	<li>
	<a href="{% url SLUG_APPENDIX_SEARCH %}?place_name={{ name }}&q=">
    {{ name }} ({{ nr }})
	</a>
	</li>
	{% endfor %}
	</ul>
</div>
{% endfor %}
{% endblock %}

apps/dasa/templates/pages/appendix-search.html
{% extends "pages/appendix-browse.html" %}
{% load url from future %}
{% load i18n highlight %}
{% block js %}
{{ block.super }}
<link href="{{ STATIC_URL }}selectable/css/dj.selectable.css" type="text/css" media="all" rel="stylesheet">
<script type="text/javascript" src="{{ STATIC_URL }}selectable/js/jquery.dj.selectable.js"></script>
<script>
    $(document).ready(function() {
    	var doc_min_date = new Date({{doc_min_year}}, {{ doc_min_month}}, {{ doc_min_day }})
    	var doc_max_date = new Date({{doc_max_year}}, {{ doc_max_month}}, {{ doc_max_day }})
    	var res_min_date = new Date({{res_min_year}}, {{ res_min_month}}, {{ res_min_day }})
    	var res_max_date = new Date({{res_max_year}}, {{ res_max_month}}, {{ res_max_day }})
        $("#id_doc_date_from").datepicker({
            changeMonth: true,
            changeYear: true,
            showButtonPanel: true,
            yearRange: '{{ doc_min_year }}:{{ doc_max_year }}',
            defaultDate: doc_min_date
        });
        $("#id_doc_date_to").datepicker({
            changeMonth: true,
            changeYear: true,
            showButtonPanel: true,
            yearRange: '{{ doc_min_year }}:{{ doc_max_year }}',
            defaultDate: doc_max_date
        });

        $("#id_res_date_from").datepicker({
            changeMonth: true,
            changeYear: true,
            showButtonPanel: true,
            yearRange: '{{ res_min_year }}:{{ res_max_year }}',
            defaultDate: res_min_date
    });
        $("#id_res_date_to").datepicker({
            changeMonth: true,
            changeYear: true,
            showButtonPanel: true,
            yearRange: '{{ res_min_year }}:{{ res_max_year }}',
            defaultDate: res_max_date
        });

    });
</script>
{% endblock %}

{% block search_form %}
    <div id="search_container" class="search_container_appendix">
        <div id="search_box">
            <form method="get" action="." id="search_resolution">
                <table>
                    {{ form.as_table }}
                    <tr>
                        <td>&nbsp;</td>
                        <td>
                            <input type="submit" value="{% trans "Search" %}">
                            <input type="reset" value="{% trans "Reset" %}"
                                onclick="frm=$('#search_resolution');resetForm(frm);frm.submit();return false;" >
                        </td>
                    </tr>
                </table>
           </form>
        </div>
    </div>
    <br class="clear" />
    <div class="tagcloud_box tagcloud_box_appendix tagcloud_box_appendix_documenttype">
        {% include "widgets/appendix-documenttype-tagcloud.html" %}
    </div>
    <br class="clear" />
    <div class="tagcloud_box tagcloud_box_appendix" >
        {% include "widgets/appendix-vessel-tagcloud.html" %}
    </div>
    <div class="tagcloud_box tagcloud_box_appendix">
        {% include "widgets/appendix-europeannames-tagcloud.html" %}
    </div>
    <br class="clear" />
    <div class="tagcloud_box tagcloud_box_appendix">
        {% include "widgets/appendix-asiannames-tagcloud.html" %}
    </div>
    <div class="tagcloud_box tagcloud_box_appendix">
        {% include "widgets/appendix-placenames-tagcloud.html" %}
    </div>
    <br class="clear" />

    <div id="search_description">
    {% if query_prettyprinted %}
        {% trans "You searched for" %}: {{ query_prettyprinted|safe }}.
    {% endif %}
	    {% with paginator_page.paginator.count as count %}
        {% blocktrans  %}We found {{ count }} results{% endblocktrans %}.
        {% endwith %}
        <a href="" onclick="$('#search_container').show(500);$('.tagcloud_box').show(500);$('#show').hide();$('#hide').show();return false;" id="show" style="display:none">
	        {% trans "show search form" %}</a>
        <a href="" onclick="$('#search_container').hide(500);$('.tagcloud_box').hide(500);$('#show').show();$('#hide').hide();return false;" id="hide">
	        {% trans "hide search form" %}
	    </a>
    </div>

<br class="clear" clear="both" />

{% endblock search_form %}

apps/dasa/templates/pages/collections.html
{% extends "basicpage_with_readmore.html" %}
{% load thumbnail i18n %}

{% block content %}
{{ block.super }}
{% comment %}
Inventory - archive general resolutions
{% endcomment %}
<table class="table_data">
<tr class="headers">
	<th style="width:140px">{% trans "Inventory Number" %}</th>
	<th>{% trans "Date period" %}</th>
	<th colspan="3" style="width:240px">{% trans "Image viewer" %}</th>
</tr>
{% for book in books %}
<tr>
    <td>{{ book.archiveFile }}</td>
    <td>{{ book.title }}</td>
    {% comment %}
        <td>{{ book.description }}</td>
    {% endcomment %}
    <td width="90px">
        <a href="#" onClick="return openPageBrowser('{{ book.link_to_pagebrowser_id }}')"
           class="link_to_pagebrowser">{% trans "Indonesian [short]" %}
	    <img class="icon" src="{{ STATIC_URL }}images/book.png"></img></a>
    </td>
    <td width="70px">
        <a href="#" onClick="return openPageBrowser('{{ book.link_to_pagebrowser_en }}')"
            class="link_to_pagebrowser">{% trans "English [short]" %}
	    <img class="icon" src="{{ STATIC_URL }}images/book.png"></img></a>
    </a></td>
    <td width="70px">
        <a href="#" onClick="return openPageBrowser('{{ book.link_to_pagebrowser_nl }}')"
            class="link_to_pagebrowser">{% trans "Dutch [short]" %}
	    <img class="icon" src="{{ STATIC_URL }}images/book.png"></img></a>
    </a>
    </td>
</tr>

{% endfor %}
</table>
<div class="hr_dotted"></div>

{% endblock %}

apps/dasa/templates/pages/corpusdiplomaticum-contracts-browse.html
{% extends "browse-and-search-template.html" %}
{% load thumbnail i18n highlight snippet %}
{% block js %}
{{ block.super }}
<script>
  $(document).ready(function() {
    $(document).tooltip();
  });
</script>
{% endblock %}

{% block headers %} 
    <tr class="headers"> 
        <th style="width:90pt"><a href=".?{{ qs.order_by_volume }}">{% trans "Volume" %}</a></th>
        <th style="width:60pt"><a href=".?{{ qs.order_by_dateFrom }}">{% trans "Date" %}</a></th>
        <th>{% trans "Description" %}</th>
        <th style="width:50pt"><a href=".?{{ qs.order_by_areaName }}">{% trans "Area" %}</a></th>
    </tr>
{% endblock headers %} 
 

{% block result_row %}
    <tr {% ifequal selected_order result.object.order %}class="selected"{% endifequal %}> 
        <td>
           <a href="#" onClick="return openPageBrowser('{{result.object.link_to_pagebrowser}}');">
            {% trans "Volume" %} {{ result.object.volumeNumber}}, {% trans "page" %} {{ result.object.pageFrom}}{% if result.object.pageTo %}-{% endif %}{{result.object.pageTo}}{% if result.object.pageSupp %}</a>{% if result.object.pageSupp %}, 
            <a href="{{result.object.link_to_pagebrowser_pageSupp}}" target="_pagebrowser">{{ result.object.pageSupp}}</a>{% endif %}
            {% endif %}

        </td>
        <td>
        {{ result.object.print_dateFrom}} 
       {% if result.object.print_dateTo %}
        - {{ result.object.print_dateTo }}
        {% endif %}
        </td>
        <td>
            {% trans "contract number" %}: {{ result.object.numberRoman }} - {{ result.object.numberDigits }}<br>
            {% trans "name kingdom" %}: {{ result.object.kingdomName }}<br>
            {% trans "description" %}:  {{ result.object.contractSourceDescription }}<br>
            {% trans "place signed" %}:  {{ result.object.signedPlace }}<br>
            {% if result.object.signedAsians %}
            {% trans "signed by Asians" %}: {{ result.object.signedAsians }} <br>
            {% endif %}
            {% if result.object.signedEuropeans %}
            {% trans "signed by Europeans" %}: {{ result.object.signedEuropeans }}  <br>
            {% endif %}
        </td>
        <td> 
        {% if result.object.areaName %}
            <a href="{% url SLUG_CORPUSDIPLOMATICUM_CONTRACTS_SEARCH %}?areaName={{ result.object.areaName}}">{{ result.object.areaName }} </a>
        {% endif %}
        </td>
    </tr>
{% endblock %}
 
 

apps/dasa/templates/pages/corpusdiplomaticum-places.html
{% extends "basicpage.html" %}
{% load url from future %}
{% load thumbnail i18n %}

{% block content %}
{{ block.super }}
<div class="alphabet">
    {% for letter, count in letters %}
    <a href="{% url SLUG_CORPUSDIPLOMATICUM_PLACES %}?first_letter={{ letter }}">
        <span class="letter">{{letter}}</span>
        <br>
        <span class="count">
        {{ count }}
        </span>
    </a>
    {% endfor %}
</div>
<br class="clear" />
{% for col in persons %}
    <div class="twocolumns column">
    <ul>

    {% for place in col %}
    <li>
    {{ place.name }}{% if place.ref %},  {% trans "see also" %} {{ place.ref }}{% endif %}
    {{ place.prettyprint_volumePage }} 
    </li>
    {% endfor %}
    </ul>
</div>
{% endfor %}
{% endblock %}

apps/dasa/templates/pages/diplomaticletters-search.html
{% extends "pages/diplomaticletters-browse.html" %}
{% load url from future %}
{% load i18n highlight %}
{% block js %}
{{ block.super }}
<link href="{{ STATIC_URL }}selectable/css/dj.selectable.css" type="text/css" media="all" rel="stylesheet">
<script type="text/javascript" src="{{ STATIC_URL }}selectable/js/jquery.dj.selectable.js"></script>
<script>
    $(document).ready(function() {
	    min_date = new Date({{min_year}}, {{ min_month}}, {{ min_day }})
	    max_date = new Date({{max_year}}, {{ max_month}}, {{ max_day }})
	    $("#id_date_from").datepicker({
	        changeMonth: true,
	        changeYear: true,
	        showButtonPanel: true,
	        yearRange: '{{ min_year }}:{{ max_year }}',
	        defaultDate: min_date
	    });
	    $("#id_date_to").datepicker({
	        changeMonth: true,
	        changeYear: true,
	        showButtonPanel: true,
	        yearRange: '{{ min_year }}:{{ max_year }}',
	        defaultDate: max_date
	    });
	});
</script>
{% endblock %}

{% block search_form %}
<script>

</script>

<div id="search_container">
    <div id="search_box">
        <form method="get" action="." id="search_resolution">
            <table>
                {{ form.as_table }}
                <tr>
                    <td>&nbsp;</td>
                    <td>
                        <input type="submit" value="{% trans "Search" %}">
                        <input type="reset" value="{% trans "Reset" %}"
                            onclick="frm=$('#search_resolution');resetForm(frm);frm.submit();return false;" >
                    </td>
                </tr>

            </table>
       </form>
    </div>
</div>

<div class="tagcloud_box">
    {% include "widgets/diplomaticletters-locations-tagcloud.html" %}
</div>
<div class="tagcloud_box">
    {% include "widgets/diplomaticletters-rulers-tagcloud.html" %}
</div>
<br class="clear" />

<div id="search_description">
    {% if query_prettyprinted %}
        {% trans "You searched for" %}: {{ query_prettyprinted|safe }}.
    {% endif %}
    {% with paginator_page.paginator.count as count %}
        {% blocktrans  %}We found {{ count }} results{% endblocktrans %}.
    {% endwith %}
    <a href="" onclick="$('#search_container').show(500);$('.tagcloud_box').show(500);$('#show').hide();$('#hide').show();return false;" id="show" style="display:none">
        {% trans "show search form" %}</a>
    <a href="" onclick="$('#search_container').hide(500);$('.tagcloud_box').hide(500);$('#show').show();$('#hide').hide();return false;" id="hide">
        {% trans "hide search form" %}
    </a>
</div>

<br class="clear" clear="both" />

{% endblock search_form %}